### ISSUE TITLE
 Can't find files for functions

### ISSUE THREAD

**Issue by ksenia1602** [priyanka8993/EMT_score_calculation#1]
Good day. For my article I am trying to reproduce your work published at https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7100584/. But the code doesn't work because EMT76GS and KSScore function require "./Gene_Signatures/KS/EM_gene_signature_cellLine.xlsx" files. Could you drop them or tell me where they are. Thank you in advance for your cooperation)

**Comment by priyanka8993** [comment]
Hi ksenia1602, 
Could you please change the file name in the function to  "EM_gene_signature_cellLine_KS.xlsx" and retry ?
