### ISSUE TITLE
RNA-seq data 

### ISSUE THREAD

**Issue by hunger105** [priyanka8993/EMT_score_calculation#3]
Hi priyanka
perfect work, I wonder if this EMT score can be applied for RNA-seq data (e.g., TCGA data, GEO RNA-seq data and my own RNA-seq data)? 
 If it works, is there anything I need to be careful of?

**Comment by hunger105** [comment]
AND for function "mlrEMTPred", argument "gpl_id" seems not been used, 
for function "getNCIindices", file  "../../Gene_signatures/MLR/GPL570-55999.txt" can not be found, which is needed to generate the matlab script.
So, if I want to use MLR method to calculate my own RNA-seq data, how could I realise it. 
Thanks a lot.

**Comment by priyanka8993** [comment]
This code is only for the microarray data downloaded from ncbi GEO website.
