### ISSUE TITLE
function "mlrEMTPred"

### ISSUE THREAD

**Issue by WangJian99** [priyanka8993/EMT_score_calculation#4]
Hi priyanka,

perfect work,  for function "mlrEMTPred", file  "../../MLR_Matlab_Code/EMT_automated.m" can not be found, which is needed to run the matlab script. Could you drop them or tell me where they are.

Thanks a lot.

**Comment by happy-nobug** [comment]
same question

**Comment by priyanka8993** [comment]
uploaded the matlab scripts
